version: '3.8'
services:
  database:
    container_name: lightning-database
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lightning-database
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
    driver: local
